### ISSUE TITLE
Does this work with UE5?

### ISSUE THREAD

**Issue by delebash** [NachoideV2/UnrealBoostCompiler#2]

**Comment by Nachoidev2** [comment]
I tested it and it works

**Comment by delebash** [comment]
cool. Ty.

**Comment by delebash** [comment]
In UE5 my shaders are compiling but in Boost after I click run it says compiler not running even though I know UE5 is compiling.  Any thoughts?

**Comment by Nachoidev2** [comment]
Yes, it was my mistake in the code, I have fixed it and uploaded the new version of the program.

**Comment by delebash** [comment]
Cool, ty.
